.TH XDUMP 1 "September 2021" "0.1.0" "User Commands"
.SH NAME
xdump \- display file contents in hexadecimal and ASCII
.SH SYNOPSIS
.B xdump
[\fB\-hv\fR] [\fB\-ac\fR] [\fB\-w\fR \fIcolumns\fR] [\fB\-s\fR \fIoffset\fR] [\fB\-n\fR \fIlength\fR] [\fIfile\fR]
.SH DESCRIPTION
The
.B xdump
utility is a filter which displays the specified file, or standard input if no file is specified, in hexadecimal and ASCII format. It works like \fBhexdump -C\fR by default.
.SH OPTIONS
.TP
.BR \-a
Adjust the number of columns (bytes) based on the terminal width.  If fail, fall back to 16 columns.
.TP
.BR \-c
Colorize the output (hexadecimal and ASCII). Printable characters are green; whitespace, yellow; NUL, gray; and ASCII characters are blue.
.TP
.BR \-w " " \fIcolumns\fR
Number of \fIcolumns\fR (bytes) to show in one row. Default is 16, which fits into a terminal 80 characters wide.
.TP
.BR \-s " " \fIoffset\fR
Skip \fIoffset\fR bytes from the beginning of the input.
.TP
.BR \-n " " \fIlength\fR
Interpret only \fIlength\fR bytes of input.
.TP
.BR \-v
Display version information and exit.
.TP
.BR \-h
Display help text and exit.
.SH AUTHOR
Written by Gustavo Costa <xfgusta@gmail.com>.
.SH REPORTING BUGS
GitHub issues: https://github.com/xfgusta/xdump/issues.
.SH COPYRIGHT
MIT License

Copyright (c) 2021 Gustavo Costa.
